import type { ClassId, Vec } from './index.js';
export type MobKind='zombie'|'wolf'|'skeleton'|'brute'|'cryptGuardian';
export type UpgradeRarity='common'|'rare'|'epic';
export type UpgradeId='power'|'vitality'|'haste'|'speed'|'regeneration'|'resistance'|'secondChance'|'reviveAlly'|'archerProjectiles'|'mageElements'|'necromancerArmy'|'guardianVigor'|'vanguardMastery';
export interface PlayerUpgradeState{damage:number;maxHpBonus:number;cooldownReduction:number;speed:number;resistance:number;regenRank:number;regenLeft:number;selfRevives:number;classRanks:Partial<Record<ClassId,number>>;stacks:Partial<Record<UpgradeId,number>>}
export interface UpgradeOption{key:string;id:UpgradeId;rarity:UpgradeRarity;title:string;description:string;value:number;reviveTargets?:{id:string;name:string}[]}
export interface UpgradeOffer{id:string;wave:number;choices:UpgradeOption[];deadline:number}
export interface Mob extends Vec{id:string;kind:MobKind;hp:number;maxHp:number;angle:number;speed:number;damage:number;attackCd:number;specialCd:number;windup:number;spawnLeft:number;frozenLeft:number;target:string|null;elite:boolean;boss:boolean;bushId:string|null;revealLeft:number}
export interface MobProjectile extends Vec{id:number;owner:string;angle:number;speed:number;damage:number;life:number;radius:number}
export interface PveState{objective:'elimination';wave:number;initialPartySize:number;pendingBudget:number;spawnedAll:boolean;enemiesRemaining:number;rewardLeft:number;chosen:string[];completed:boolean;endless:boolean;bossActive:boolean;kills:Record<string,number>;damage:Record<string,number>}
export const emptyUpgrades=():PlayerUpgradeState=>({damage:0,maxHpBonus:0,cooldownReduction:0,speed:0,resistance:0,regenRank:0,regenLeft:0,selfRevives:0,classRanks:{},stacks:{}});
export const MOB_STATS:Record<MobKind,{hp:number;damage:number;speed:number;cost:number;range:number;cooldown:number;radius:number}>={zombie:{hp:2,damage:.5,speed:90,cost:1,range:25,cooldown:1.2,radius:12},wolf:{hp:1.5,damage:.5,speed:190,cost:1.3,range:23,cooldown:.9,radius:13},skeleton:{hp:1.5,damage:.5,speed:75,cost:1.5,range:250,cooldown:1.8,radius:11},brute:{hp:6,damage:1,speed:70,cost:3.5,range:46,cooldown:2.2,radius:19},cryptGuardian:{hp:35,damage:1.5,speed:68,cost:0,range:58,cooldown:1.7,radius:27}};
export const waveBudget=(wave:number,party:number)=>Math.round((3+1.8*(wave-1))*(1+.65*(Math.max(1,party)-1)));
export function availableMobs(wave:number):MobKind[]{if(wave<=1)return['zombie'];if(wave===2)return['zombie','wolf'];if(wave===3)return['zombie','wolf','skeleton'];return['zombie','wolf','skeleton','brute']}
const tiers={common:{damage:.10,hp:.15,haste:.08,speed:.05,resistance:.08},rare:{damage:.20,hp:.25,haste:.12,speed:.08,resistance:.12},epic:{damage:.30,hp:.40,haste:.18,speed:.12,resistance:.18}} as const;
const classCards:Record<ClassId,[UpgradeId,string,string]>={archer:['archerProjectiles','Viento certero','Flechas más veloces y trampas más amplias.'],mage:['mageElements','Núcleo elemental','Aumenta el alcance del hielo y las explosiones.'],necromancer:['necromancerArmy','Legión impía','Fortalece invocaciones y amplía su límite.'],guardian:['guardianVigor','Acero imparable','Mejora embestida, espada y movimiento en guardia.'],vanguard:['vanguardMastery','Maestría pesada','Amplía ataques, giro y ventana de parry.']};
function rollRarity(wave:number,random:()=>number):UpgradeRarity{const bonus=Math.min(12,Math.max(0,wave-5)*2),roll=random()*100;if(roll<8+bonus*.35)return'epic';if(roll<35+bonus)return'rare';return'common'}
export function makeUpgradeChoices(classId:ClassId,state:PlayerUpgradeState,wave:number,random:()=>number=Math.random,reviveTargets:{id:string;name:string}[]=[],forceRevive=false):UpgradeOption[]{
 const [classUpgrade,classTitle,classDescription]=classCards[classId];const pool:UpgradeId[]=['power','vitality','haste','speed','regeneration','resistance','secondChance',classUpgrade];
 const valid=pool.filter(id=>id==='power'?state.damage<1:id==='vitality'?state.maxHpBonus<.75:id==='haste'?state.cooldownReduction<.4:id==='speed'?state.speed<.25:id==='resistance'?state.resistance<.35:id==='regeneration'?state.regenRank<3:id==='secondChance'?state.selfRevives<1:(state.classRanks[classId]??0)<3);
 const selected:UpgradeId[]=[];if(forceRevive&&reviveTargets.length)selected.push('reviveAlly');while(selected.length<3&&valid.length){const id=valid.splice(Math.floor(random()*valid.length),1)[0];if(!selected.includes(id))selected.push(id)}while(selected.length<3)selected.push((['power','vitality','haste'] as UpgradeId[])[selected.length]);
 return selected.map((id,index)=>{const rarity:UpgradeRarity=id==='reviveAlly'||id==='secondChance'?'epic':rollRarity(wave,random),t=tiers[rarity],base={key:`${wave}:${index}:${id}`,id,rarity};
  if(id==='power')return{...base,title:'Fuerza',description:`+${t.damage*100}% de daño.`,value:t.damage};if(id==='vitality')return{...base,title:'Vitalidad',description:`+${t.hp*100}% de vida máxima y cura inmediata.`,value:t.hp};if(id==='haste')return{...base,title:'Celeridad',description:`-${t.haste*100}% a las recargas.`,value:t.haste};if(id==='speed')return{...base,title:'Paso ligero',description:`+${t.speed*100}% de movimiento.`,value:t.speed};if(id==='resistance')return{...base,title:'Armadura',description:`-${t.resistance*100}% de daño recibido.`,value:t.resistance};if(id==='regeneration')return{...base,title:'Regeneración',description:`Rango ${state.regenRank+1}: recupera vida fuera del combate.`,value:state.regenRank+1};if(id==='secondChance')return{...base,title:'Segunda oportunidad',description:'Una vez: revivís tras 2 s con 40% de vida.',value:1};if(id==='reviveAlly')return{...base,title:'Revivir compañero',description:'Elegí un aliado; vuelve con 50% de vida.',value:1,reviveTargets};return{...base,title:classTitle,description:classDescription,value:rarity==='epic'?.2:rarity==='rare'?.14:.09};
 });
}
